const logourl = `../assets/images/`

export const localImage = {
    LOGO: require(`${logourl}logo.png`),
    LOCATIONICON: require(`${logourl}locationIcon.png`),
    ROOM: require(`${logourl}room.png`),
    BACKBUTTON: require(`${logourl}backBtn.png`),
    GOOGLE: require(`${logourl}google.png`),
    FACEBOOK: require(`${logourl}facebook.png`),
    APPLE: require(`${logourl}apple.png`),
    HOMEGROUP: require(`${logourl}homeGroup.png`),
    KITCHEN: require(`${logourl}kitchen.png`),
    SETTINGS: require(`${logourl}settings.png`),
    PHONE: require(`${logourl}phone.png`),
    BED: require(`${logourl}bed.png`),
    Heart: require(`${logourl}heart.png`),
    BUILDING: require(`${logourl}building.png`),
    LOCATION: require(`${logourl}location.png`),
    USER: require(`${logourl}user.png`),
    STAR: require(`${logourl}star.png`),
    PG: require(`${logourl}pg.png`),
    NOTIFICATIONIMG: require(`${logourl}notificationImg.jpg`),
    PGIMAGE: require(`${logourl}pgimage.png`),
    CAR: require(`${logourl}car.png`),
    SIZEICON: require(`${logourl}sizeIcon.png`),
    COLOREDBED: require(`${logourl}coloredBed.png`),
    COLOREDLOCATION: require(`${logourl}coloredLocation.png`),
    COLOREDPHONE: require(`${logourl}coloredPhone.png`),
    RESET: require(`${logourl}reset.png`),
    MIC: require(`${logourl}mic.png`),
    SEARCH: require(`${logourl}search.png`),
    DROPDOWN: require(`${logourl}dropdown.png`),
    NOTIFICATIONBALL: require(`${logourl}notification.png`),
    NOTIFICATIONCIRCLE: require(`${logourl}notificationcircle.png`),
    PROPERTY: require(`${logourl}property.png`),
    FLATE: require(`${logourl}flate.png`),
    PENCIL: require(`${logourl}pencil.png`),
    LOGOUT: require(`${logourl}logout.png`),
}